### PR TITLE
feat: build feedback funnel

### PR DESCRIPTION
**Pull request by Namyalg**
# Description

The feedback funnel has been integrated into the Sphinx documentation. 

- [X] Issue reference: #185 
- [X] Preview Links: https://moja-global-documentation--186.org.readthedocs.build/en/186/FLINT/UnderstandingFLINT/index.html
- [X] Explain the changes: A feedback template `feedback.rst` has been created, this will be included in every rst file. It has a textarea to enter feedback and an option for the user to choose the documentation was helpful or not
- [X] Dependency changes: A javascript file, `script.js` has been added in the `sources/_script` folder to collect feedback

The Google Sheets link where feedback is collected : https://docs.google.com/spreadsheets/d/1BZSnkb2n-f9Igt5H8rctCsf7FSSfLbjZojp4ZDEYjmQ/edit?usp=sharing

Thanks for opening the Pull Request for moja global. Happy contributing ✨

### CODE REVIEW

**Comment by Namyalg** [comment]
The buttons, `Yes`, `No`, `Send feedback` and the `text area` styling are controlled by the browser level style sheet. Custom styling can be added in case it is needed

**Comment by Namyalg** [comment]
https://user-images.githubusercontent.com/53875297/170833853-353cfe31-2612-4c17-8951-ade7b2ab8ada.mp4

A short video going over the working of the feedback funnel

**Review by shubhamkarande13 — APPROVED** [review]
Well done!

**Comment by Namyalg** [comment]
The PR is ready.
The end of every section has a `section-feedback` form
While for a page that includes installation details each page has a feedback form

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
