### PR TITLE
added greeting bot

### LINKED ISSUE #70: Greeting Bot
Adding Greeting Bot to the repo which will Greet new contributors and greet everyone on their PR merged.

### PR DESCRIPTION
**Pull request by Sukriti-sood**
Fixes #70

### CODE REVIEW

**Comment by HarshCasper** [comment]
Hi @Sukriti-sood 

Can you please fix the DCO? Just run the following commands: 


```
git commit --amend --no-edit --signoff
git push --force-with-lease origin issue-forms
```

**Comment by Sukriti-sood** [comment]
@HarshCasper done

**Comment by shubhamkarande13** [comment]
@HarshCasper Can we merge this PR?

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Hi @Sukriti-sood 

We already have a `config,yml` that does the exact the same thing here: https://github.com/moja-global/moja_global_docs/blob/master/.github/config.yml

How does this improve our processes?

**Comment by Sukriti-sood** [comment]
> Hi @Sukriti-sood
> 
> We already have a `config,yml` that does the exact the same thing here: https://github.com/moja-global/moja_global_docs/blob/master/.github/config.yml
> 
> How does this improve our processes?

Not much , only the advantage is it will comment on every merged PR.

**Pull request closed without merging**
