### PR TITLE
Clarify FLINT prerequisites

### PR DESCRIPTION
**Pull request by sarahhaggarty**
## Description

This PR is a proposal to make changes to the existing documentation to make it more explicit to the reader when to fork and clone FLINT core repository as part of the installation process. For further details and motivation please read: #57 

Fixes # (issue)
#57 

## Type of change

Please delete options that are not relevant.

- [x] This change is a documentation update

## How Has This Been Tested?

N/A

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by sarahhaggarty** [comment]
Hi @HarshCasper @shubhamkarande13 @aornugent,

Would you be able to review this PR?

**Comment by aornugent** [comment]
Could you please take a look at this @shubhamkarande13 - it should be very familiar after creating your videos!

**Comment by sarahhaggarty** [comment]
Hi @shubhamkarande13 @chicken-biryani, thank you so much for your time earlier this week to discuss this PR. It was really helpful! As we discussed, I created two new issues: #59 and #60.

I reverted my suggested change about moving "Data Sets" to FLINT.example from this PR so that issue can be followed instead on #60.

This leaves the following changes that we spoke about:
- Removed the statement about FLINT.example completely in [DevelopmentSetup/index.rst](https://github.com/moja-global/moja_global_docs/blob/master/docs/DevelopmentSetup/index.rst) so that readers will continue to the next page which is the "Git and Github Guide" where they are instructed to fork and clone FLINT core repository. This will prevent them from making the same mistake that I made.
- Amended the statement in [DevelopmentSetup/FLINT.example_installation.rst](https://github.com/moja-global/moja_global_docs/blob/master/docs/DevelopmentSetup/FLINT.example_installation.rst) to: "It is recommended to practice running simulations using FLINT.example repository after the FLINT core installation is completed. This will help you to familiarise yourself with FLINT and help you to understand how FLINT works."
- Added in the prerequisites sections of the below pages that relevant FLINT core and FLINT.example repositories need to be forked and cloned before proceeding:
[DevelopmentSetup/windows_installation.rst](https://github.com/moja-global/moja_global_docs/blob/master/docs/DevelopmentSetup/windows_installation.rst)
[DevelopmentSetup/visual_studio_win_example.rst](https://github.com/moja-global/moja_global_docs/blob/master/docs/DevelopmentSetup/visual_studio_win_example.rst)
- Removed the instruction in [Prerequisites/vcpkg.rst](https://github.com/moja-global/moja_global_docs/blob/master/docs/prerequisites/vcpkg.rst) to build the visual studio solution because this is too early. 

I double-checked the videos and the changes I've proposed have no impact as the sections which are changed are not consulted or shown in the videos.

@shubhamkarande13 do you think you're OK to review this PR now? Let me know if there is anything I missed!

**Review by shubhamkarande13 — APPROVED** [review]

**Comment by shubhamkarande13** [comment]
Great PR @sarahhaggarty!
Thank you so much for your hard work!

**Comment by sarahhaggarty** [comment]
Thanks @shubhamkarande13 @chicken-biryani! Can one of you manually link this PR with #57? I don't have the permissions.

**Comment by HarshCasper** [comment]
@all-contributors bot please add @sarahhaggarty for docs bug mentoring review

**Pull request merged**
