### PR TITLE
docs: add study_area.json to GCBM Inputs

### PR DESCRIPTION
**Pull request by sailorworks**
Hello, I am addressing this [issue](https://github.com/moja-global/moja_global_docs/issues/194) in which I it is clearly mentioned that I have to add a missing JSON file.
Here what I did is open a JSON file in jupyter notebook and add it to directly from the system to my forked repo and I've also updated the index that is in investigating GCBM inputs.
Thank you

### CODE REVIEW

**Review by padmajabhol — CHANGES_REQUESTED** [review]
The page does not show up in preview since it doesn't have a title? You can also add a little description like we have for other JSON notebooks.

**Comment by sailorworks** [comment]
Updated with required changes
Thankyou

**Review by padmajabhol — CHANGES_REQUESTED** [review]
Nice! Just add this as description: `View JSON data parsed from study_area`

**Review by padmajabhol — APPROVED** [review]
LGTM! Thanks a lot.

**Pull request merged**
