### PR TITLE
Update coc.rst

### PR DESCRIPTION
**Pull request by aniketh-varma**
# Small fix in code of conduct

- [x] Issue reference: #165 
Changed the email under enforcement section from guy@moja.global to mentorship@moja.global

Signed-off-by: Aniketh Varma <aaniketh_varma@yahoo.com>

### CODE REVIEW

**Review by chicken-biryani — APPROVED** [review]
Thanks, @aniketh-varma!! ♥️

**Comment by aniketh-varma** [comment]
Hi, @chicken-biryani do I need to update this as well: https://github.com/moja-global/community-website/blob/main/CODE_OF_CONDUCT.md.

**Comment by chicken-biryani** [comment]
@aniketh-varma can you please run the following commands so that we can let go the bot.

 ```
git commit --amend --no-edit --signoff
 git push --force-with-lease origin master

```

**Comment by chicken-biryani** [comment]
@aniketh-varma yes. Please update that as well.

**Comment by aniketh-varma** [comment]
> @aniketh-varma can you please run the following commands so that we can let go the bot.
> 
> ```
> git commit --amend --no-edit --signoff
> git push --force-with-lease origin master
> ```

I had made edits using the GitHub editor 😅, any other way to fix this?

**Comment by chicken-biryani** [comment]
@aniketh-varma oh!

@HarshCasper is there another way around the bot?

**Comment by HarshCasper** [comment]
> @aniketh-varma oh!
> 
> @HarshCasper is there another way around the bot?

Don't worry about that!

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
