### PR TITLE
DOCS: Host python notebooks containing different data-types

### PR DESCRIPTION
**Pull request by padmajabhol**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- [x] Issue reference #160 
- [x] Subject Matter Expert (SME) reviewer: @aornugent 
- [x] Peer reviewer: @HarshCasper @chicken-biryani 
- [ ] Preview Links: 
- [x] Explain the changes: The python notebooks containing the datatypes(used as FLINT inputs) have been hosted in the sphinx site.
- [x] Dependency changes: I have used the nbsphinx extension to render the notebooks in sphinx.

Thanks for opening the Pull Request for moja global. Happy contributing ✨

### CODE REVIEW

**Comment by chicken-biryani** [comment]
Hi @padmajabhol do you think it's a good idea to specify which file you're using as an example here, if not specified already?

A new reader may get confused.

**Comment by padmajabhol** [comment]
> Hi @padmajabhol do you think it's a good idea to specify which file you're using as an example here, if not specified already?
> 
> A new reader may get confused.

I have mentioned the data types. I'll add the file name with the link.

**Comment by aornugent** [comment]
@HarshCasper - it seems publishing notebooks requires Pandoc in the CI environment:

https://github.com/moja-global/moja_global_docs/runs/5679134773?check_suite_focus=true#step:4:227

**Comment by saranda-2811** [comment]
According to line 122 of the logs, nbconvert 6.4.5 has requirement MarkupSafe>=2.0, but you'll have markupsafe 1.1.1 which is incompatible.
Could u update the requirements.txt to markupsafe with version>=2.0 and check?

https://github.com/moja-global/moja_global_docs/runs/5887538966?check_suite_focus=true

**Pull request closed without merging**
